platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
pod 'ObjectiveSugar'
pod 'MarqueeLabel', '~> 2.2'
pod 'Reachability', '~> 3.2'
pod 'SpinKit', '~> 1.1'
pod 'JTSlideShadowAnimation', '~> 1.0'
pod 'BSErrorMessageView', :git => 'https://github.com/BenjaminSarkisyan/BSErrorMessageView.git'
pod 'FRDLivelyButton', '~> 1.1.3'