platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
pod 'MarqueeLabel', '~> 2.2'
pod 'Reachability', '~> 3.2'
pod 'SpinKit', '~> 1.1'
pod 'JTSlideShadowAnimation', '~> 1.0'
pod 'BSErrorMessageView', :git => 'https://github.com/BenjaminSarkisyan/BSErrorMessageView.git'
pod 'FRDLivelyButton', '~> 1.1.3'
pod 'HTMLAttributedString', '~> 0.0.1'
pod 'LMDropdownView', '~> 1.0.2'
pod 'FBSDKCoreKit', '~> 4.7'
pod 'FBSDKLoginKit', '~> 4.7'
pod 'FBSDKShareKit', '~> 4.7'
pod 'PinterestSDK', :git => 'https://github.com/pinterest/ios-pdk.git'
pod 'Flurry-iOS-SDK/FlurrySDK'